#!/bin/bash
# Short Publisher — bootstrap key generator
# Generates the 3 random secrets needed to get started and writes them to .env.local

set -e

echo ""
echo "Short Publisher — Setup"
echo "========================"

if ! command -v openssl &>/dev/null; then
  echo "ERROR: openssl is required. Install it first."
  exit 1
fi

PIPELINE_KEY=$(openssl rand -hex 16)
AUTH_TOKEN=$(openssl rand -hex 32)
DASHBOARD_PW="sp-$(openssl rand -hex 6)"

echo ""
echo "Generated keys:"
echo "  PIPELINE_SECRET_KEY  = $PIPELINE_KEY"
echo "  AUTH_TOKEN           = $AUTH_TOKEN"
echo "  DASHBOARD_PASSWORD   = $DASHBOARD_PW"

# Write .env.local (don't overwrite DATABASE_URL if file already exists)
ENV_FILE="$(dirname "$0")/../.env.local"

if [ -f "$ENV_FILE" ]; then
  echo ""
  echo ".env.local already exists — updating keys (DATABASE_URL preserved)."
  # Remove old generated keys if present
  grep -v "^PIPELINE_SECRET_KEY=" "$ENV_FILE" | \
  grep -v "^AUTH_TOKEN=" | \
  grep -v "^DASHBOARD_PASSWORD=" > "${ENV_FILE}.tmp" && mv "${ENV_FILE}.tmp" "$ENV_FILE"
  {
    echo "PIPELINE_SECRET_KEY=$PIPELINE_KEY"
    echo "AUTH_TOKEN=$AUTH_TOKEN"
    echo "DASHBOARD_PASSWORD=$DASHBOARD_PW"
  } >> "$ENV_FILE"
else
  cat > "$ENV_FILE" << EOF
# Fill in your NeonDB connection string below
DATABASE_URL=postgresql://user:pass@ep-xxx.neon.tech/neondb?sslmode=require

# Generated by setup.sh — do not share these
PIPELINE_SECRET_KEY=$PIPELINE_KEY
AUTH_TOKEN=$AUTH_TOKEN
DASHBOARD_PASSWORD=$DASHBOARD_PW
EOF
  echo ""
  echo "Created .env.local — fill in DATABASE_URL before running npm run db:push"
fi

echo ""
echo "Next steps:"
echo "  1. Fill in DATABASE_URL in .env.local (NeonDB connection string)"
echo "  2. Run:  npm run db:push"
echo "  3. Add to Vercel env vars:  DATABASE_URL  PIPELINE_SECRET_KEY  AUTH_TOKEN  DASHBOARD_PASSWORD"
echo "  4. Add to GitHub Actions secrets:"
echo "       APP_URL             = https://your-app.vercel.app"
echo "       PIPELINE_SECRET_KEY = $PIPELINE_KEY"
echo ""
